name: deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # нужно для OIDC (Workload Identity Federation)

jobs:
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    env:
      YC_FOLDER_ID: b1g0l5td107efg2qqtbt
      YC_REGISTRY_ID: crpcops913ligth564mi
      YC_IMAGE_REPO: llm-course-yandex-handbook-rag-bot
      YC_CONTAINER_NAME: ml-handbook-bot
      YC_RUNTIME_SA_ID: ajeelda3qd5t8elth1m0
      LOCKBOX_SECRET_ID: e6qtuem2r17r91u9pv5q
      WEBHOOK_URL: https://bba80maqfph0m101pd4l.containers.yandexcloud.net

    concurrency:
      group: sls-container-deploy
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yc CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
          export PATH="$HOME/yandex-cloud/bin:$PATH"
          yc --version

      - name: Get Yandex Cloud IAM token via WIF (GitHub OIDC)
        id: get_iam_token
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          yc-sa-id: ${{ secrets.YC_SA_ID }}

      - name: Configure yc (folder)
        env:
          YC_IAM_TOKEN: ${{ steps.get_iam_token.outputs.token }}
        run: |
          yc config set folder-id "${YC_FOLDER_ID}"
          yc config list

      - name: Docker login to Yandex Container Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: iam
          password: ${{ steps.get_iam_token.outputs.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            cr.yandex/${{ env.YC_REGISTRY_ID }}/${{ env.YC_IMAGE_REPO }}:${{ github.sha }}
            cr.yandex/${{ env.YC_REGISTRY_ID }}/${{ env.YC_IMAGE_REPO }}:latest

      - name: Deploy Serverless Container revision
        env:
          YC_IAM_TOKEN: ${{ steps.get_iam_token.outputs.token }}
        run: |
          IMAGE="cr.yandex/${YC_REGISTRY_ID}/${YC_IMAGE_REPO}:${GITHUB_SHA}"

          yc serverless container revision deploy \
            --container-name "${YC_CONTAINER_NAME}" \
            --image "${IMAGE}" \
            --service-account-id "${YC_RUNTIME_SA_ID}" \
            --cores 1 \
            --memory 4GB \
            --concurrency 1 \
            --execution-timeout 5m \
            --min-instances 1 \
            --environment WEBHOOK_URL="${WEBHOOK_URL}" \
            --secret id="${LOCKBOX_SECRET_ID}",key=TELEGRAM_BOT_TOKEN,environment-variable=TELEGRAM_BOT_TOKEN \
            --secret id="${LOCKBOX_SECRET_ID}",key=OPENROUTER_API_KEY,environment-variable=OPENROUTER_API_KEY
